# Generated by Django 4.2.30 on 2026-09-05 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='ID sesi dari consumer (mis. HealthTalk). Unik lintas consumer.', max_length=128, unique=True)),
                ('consumer', models.CharField(default='healthify', help_text='Nama consumer: healthify | healthtalk | <lainnya>', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=16)),
                ('health_context', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['session_id'], name='api_convers_session_3f4d56_idx'), models.Index(fields=['consumer', 'status'], name='api_convers_consume_980a6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsultationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True, default='')),
                ('payload', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='api.conversationsession')),
            ],
            options={
                'verbose_name_plural': 'Consultation summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=16)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, default='', max_length=48)),
                ('evidence_status', models.CharField(blank=True, default='', max_length=32)),
                ('safety_decision', models.CharField(blank=True, default='', max_length=16)),
                ('evidence_refs', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversationsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='api_convers_session_4f4fcb_idx')],
            },
        ),
    ]
