# Generated by Django 4.2.30 on 2026-09-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_conversationsession_consultationsummary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationresult',
            name='logic_version',
            field=models.CharField(default='v3.0', help_text='Versi mesin yang menghasilkan penilaian ini. Hasil dari versi lama tidak disajikan dari cache.', max_length=32, null=True),
        ),
    ]
