# Generated by Django 4.2.30 on 2026-09-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_bump_logic_version_v32'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, default='', max_length=200)),
                ('use_case', models.TextField()),
                ('expected_volume', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Menunggu peninjauan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], db_index=True, default='pending', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API access request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(blank=True, default='', help_text='Penanda bebas, mis. "backend produksi".', max_length=200)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(blank=True, default='', help_text='Beberapa karakter awal kunci, untuk mengenalinya tanpa menyimpan nilai aslinya.', max_length=16)),
                ('rate', models.CharField(blank=True, default='', help_text='Batas laju khusus, mis. "120/min". Kosong = batas bawaan.', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('request_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_keys', to='api.apiaccessrequest')),
            ],
            options={
                'verbose_name': 'Intelligence API key',
                'ordering': ['-created_at'],
            },
        ),
    ]
